# Do NOT update manually; changes here will be overwritten by Copier
_commit: af08ec1
_src_path: https://github.com/openg2p/openg2p-fastapi-template
github_ci_docker_build: true
github_ci_openapi_publish: true
github_ci_precommit: true
github_ci_pypi_publish: true
github_ci_tests: true
github_ci_tests_codecov: true
module_name: websub_print_listener
org_name: OpenG2P
org_slug: OpenG2P
package_name: websub-print-listener
repo_name: WebSub Print Listener
repo_slug: websub-print-listener

